"""List Update.

Revision ID: b4aa4d8e785f
Revises: 9626c9b4aa92
Create Date: 2020-12-23 19:10:26.397178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aa4d8e785f'
down_revision = '9626c9b4aa92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('dates', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'dates')
    # ### end Alembic commands ###
